return {
  cmd = { 'basedpyright-langserver', '--stdio' },
  filetypes = { 'python' },
  root_markers = { 'pyproject.toml', 'requirements.txt' },
  settings = {
    basedpyright = {
      analysis = {
        autoImportCompletions = true,
        diagnosticMode = 'openFilesOnly',
        useLibraryCodeForTypes = true,
        extraPaths = { './backend' },
        exclude = {
          '**/frontend',
          '**/node_modules',
          '**/.ruff_cache',
          '**/.mypy_cache',
          '**/.pytest_cache',
          '**/dist',
          '**/build',
          '**/__pycache__',
          '**/.venv',
          '**/venv',
          '**/.git',
          './frontend',
          './node_modules',
          './.ruff_cache',
          './.mypy_cache',
          './.pytest_cache',
          './dist',
          './build',
          './__pycache__',
          './.venv',
          './venv',
          './.git',
        },
        ignore = { '*' },
        indexing = false,
      },
    },
  },
}
